### ISSUE TITLE
deprecation warning: Setting 'locationType' to 'router-scroll'

### ISSUE THREAD

**Issue by Kira-Pilot91** [DockYard/ember-router-scroll#214]
Seeing this in version 1.2.0. I'm using Ember 3.11.

`deprecate.js:120 DEPRECATION: Setting 'locationType' to 'router-scroll' in config/environment.js is deprecated, please change it to 'auto'. If you are overriding ember-router-scroll's implementation of "pushState" or "replaceState", then you can subclass and override a new location object from: import HistoryLocation from '@ember/routing/history-location'; [deprecation id: ember-router-scroll]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:54731:23)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:54758:11)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at http://localhost:4200/assets/lightworks-tuxedo.js:19533:9
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at invoke (http://localhost:4200/assets/vendor.js:54837:11)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:54796:30)
        at Class.init (http://localhost:4200/assets/vendor.js:225295:13)`

And if I add a breakpoint at the last frame from the above trace, I am here:

`Ember.deprecate("Setting 'locationType' to 'router-scroll' in config/environment.js is deprecated, please change it to 'auto'. If you are overriding ember-router-scroll's implementation of \"pushState\" or \"replaceState\", then you can subclass and override a new location object from: import HistoryLocation from '@ember/routing/history-location';", false, {
        id: 'ember-router-scroll',
        until: '2.0.0'
      });`

Let me know if I can provide any more info! Thanks for keeping up the repo!

**Comment by CvX** [comment]
The deprecation notice says:

> Setting 'locationType' to 'router-scroll' in config/environment.js is deprecated, please change it to 'auto'.

Did you change that value in your config?

**Comment by Kira-Pilot91** [comment]
!!! My bad. I changed it, but did not restart my server. I'll close this out. Thanks for you fast reply.
