### ISSUE TITLE
deprecation warning: Setting a computed property as volatile has been deprecated

### ISSUE THREAD

**Issue by Kira-Pilot91** [DockYard/ember-router-scroll#215]
Seeing this in version 1.2.0. I'm using Ember 3.11.

`deprecate.js:120 DEPRECATION: Setting a computed property as volatile has been deprecated. Instead, consider using a native getter with native class syntax. [deprecation id: computed-property.volatile] See https://emberjs.com/deprecations/v3.x#toc_computed-property-volatile for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:54731:23)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:54758:11)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at http://localhost:4200/assets/lightworks-tuxedo.js:19533:9
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at invoke (http://localhost:4200/assets/vendor.js:54837:11)
        at deprecate (http://localhost:4200/assets/vendor.js:54796:30)
        at ComputedProperty.volatile (http://localhost:4200/assets/vendor.js:34212:46)`

And if I add a breakpoint at the last frame from the above trace, I am here:

`     Ember.deprecate("Setting 'locationType' to 'router-scroll' in config/environment.js is deprecated, please change it to 'auto'. If you are overriding ember-router-scroll's implementation of \"pushState\" or \"replaceState\", then you can subclass and override a new location object from: import HistoryLocation from '@ember/routing/history-location';", false, {
        id: 'ember-router-scroll',
        until: '2.0.0'
      });`

Let me know if I can provide any more info! Thanks for keeping up the repo!

**Comment by CvX** [comment]
ember-router-scroll is no longer using `volatile` computed properties. Are you sure that's the source of this deprecation warning?

**Comment by Kira-Pilot91** [comment]
Hmm, I see now that the breakpoint I added was only useful for the other issue I opened. I'll close this and reopen a new issue if I can get a better trace. Thanks!
